# Generated by Django 4.2 on 2025-11-09 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='家務名稱')),
                ('type', models.CharField(choices=[('PUBLIC', '公共家事'), ('PRIVATE', '私人家事')], default='PUBLIC', max_length=10, verbose_name='類型')),
                ('frequency_days', models.PositiveIntegerField(default=7, verbose_name='頻率 (天)')),
                ('last_completed', models.DateField(default=datetime.date.today, verbose_name='上次完成日期')),
                ('private_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='私人家務區域')),
                ('assigned_to', models.ManyToManyField(related_name='assigned_chores', to=settings.AUTH_USER_MODEL, verbose_name='負責成員')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='rooms.room', verbose_name='所屬房號')),
            ],
            options={
                'verbose_name': '家務事項',
                'verbose_name_plural': '家務事項',
                'ordering': ['last_completed'],
            },
        ),
        migrations.CreateModel(
            name='ChoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(auto_now_add=True, verbose_name='實際完成時間')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='chores.chore', verbose_name='家務事項')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='完成者')),
            ],
            options={
                'verbose_name': '家務完成紀錄',
                'verbose_name_plural': '家務完成紀錄',
                'ordering': ['-completed_on'],
            },
        ),
    ]
