# Generated by Django 4.2 on 2025-11-10 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='last_completed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='上次完成日期'),
        ),
    ]
