# Generated by Django 5.1.1 on 2025-12-20 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_alter_chore_last_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
    ]
