# Generated by Django 4.2 on 2025-11-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='標題 (文章專用)')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_article', models.BooleanField(default=True, verbose_name='是否為文章 (True=文章, False=留言/回覆)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_and_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chats.chat', verbose_name='父級文章/留言')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='rooms.room', verbose_name='所屬房號')),
            ],
            options={
                'verbose_name': '留言板訊息',
                'verbose_name_plural': '留言板訊息',
                'ordering': ['-created_at'],
            },
        ),
    ]
