# Generated by Django 4.2 on 2025-11-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True, verbose_name='房號')),
                ('password', models.CharField(max_length=128, verbose_name='房號密碼 (儲存 Hashed 值)')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('members', models.ManyToManyField(related_name='joined_rooms', to=settings.AUTH_USER_MODEL, verbose_name='房號成員')),
            ],
            options={
                'verbose_name': '房號',
                'verbose_name_plural': '房號',
            },
        ),
    ]
